# Spring Application Name
spring.application.name=BlockVoluntariado Platform

# Default to development when no explicit profile is provided.
spring.profiles.default=${SPRING_PROFILES_ACTIVE:dev}

# Shared Spring DataSource Configuration
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Shared Spring Data JPA Hibernate Configuration
spring.jpa.hibernate.naming.physical-strategy=com.bv.platform.shared.infrastructure.persistence.jpa.configuration.strategy.SnakeCaseWithPluralizedTablePhysicalNamingStrategy

# Application Information for Documentation
documentation.application.description=@project.description@
documentation.application.version=@project.version@

# JWT Configuration Properties
authorization.jwt.secret=BlockVoluntariadoSuperSecretKeyForJwtTokenSigningCredentials2026UpcFinalProject
authorization.jwt.expiration.days=7

# i18n message bundles
spring.messages.basename=messages
spring.messages.encoding=UTF-8

# Flyway Configuration
spring.flyway.enabled=false
